### ISSUE TITLE
Helpful error messages are suppressed

### ISSUE THREAD

**Issue by gilbertsoft** [TYPO3-Console/composer-auto-commands#2]
If an error occurs during the execution of the console commands the helpful error messages are suppressed and only a error code is shown:
```
$ ddev composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 1 install, 0 updates, 0 removals
  - Installing dirkpersky/typo3-rte-ckeditor-fontawesome (10.0.0): Downloading (Downloading (100%)
Generating autoload files
Setting up TYPO3 environment and extensions.
Executing TYPO3 Console command "database:updateschema" returned with error code 255.
Executing TYPO3 Console command "cache:flush" returned with error code 255.
Executing TYPO3 Console command "extension:setupactive" returned with error code 255.
> typo3cms install:fixfolderstructure
> typo3cms install:generatepackagestates
```

If you run the command directly this is shown:
```
$ ddev composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> typo3cms database:updateschema
  [ TYPO3\CMS\Core\Cache\Exception ]
  The APCu backend cannot be used because apcu is disabled on CLI.
database:updateschema [--dry-run] [--] [<schemaUpdateTypes>]
Script typo3cms database:updateschema handling the typo3-cms-scripts event returned with error code 255
Script @typo3-cms-scripts was called via post-autoload-dump
```

Additionally to the error code it would be nice to see the exception too which will make debugging much faster especially for beginners. We had this case today in Slack see https://typo3.slack.com/archives/C8TRNQ601/p1585051552060100

**Comment by rfay** [comment]
Additionally, shouldn't the `composer install` have failed in this case instead of appearing to succeed (but with errors noted in the output)?

**Comment by gilbertsoft** [comment]
Just looked at the code and saw this information would be outputed in verbose mode.... But we should have a look at Randy's proposition

**Comment by helhum** [comment]
> Additionally, shouldn't the composer install have failed in this case instead of appearing to succeed (but with errors noted in the output)?

Yes and no. Yes, `composer install` should fail, when either `install:generatepackagestes` or `install:fixfolderstructure` fails. This needs to be fixed.

No, it must not fail when the other commands are executed, as these are "optional" commands. It would be nice if they work, as they provide a shortcut to setting up extensions automatically, but it does not harm a lot if they fail. manual intervention is still needed then.

Regarding just showing the error code. Showing the full error, when the command fails should be done, yes. Just like other exceptions in Composer show the error message on failure and the error message plus trace in verbose mode.

For the "gracefully failing" commands I'd like to keep the things like they are, since a failure isn't necessarily severe. Maybe I can change the color to yellow here to indicate a warning instead of indicating an error.
